services:
    # 1. Nginx
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        depends_on:
            - spring-api
        networks:
            - banolim-network

    # 2. Certbot
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12d & wait $${!}; done;'"
        networks:
            - banolim-network

    # 3. Spring Boot
    spring-api:
        image: ${DOCKER_HUB_USERNAME}/banolim-spring:latest
        container_name: spring-api
        restart: always
        environment:
            - SPRING_DATASOURCE_URL=${DEPLOY_DB_URL}
            - SPRING_DATASOURCE_USERNAME=${DEPLOY_DB_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${DEPLOY_DB_PASSWORD}
            - APP_FRONTEND_URL=${FRONTEND_URL}
            - JWT_SECRET=${JWT_SECRET}
            - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
            - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}

            # FastAPI 서비스 이름으로 연결 (도커 내부망)
            - FASTAPI_BASE_URL={FASTAPI_BASE_URL}
        depends_on:
            - fastapi-ai
        networks:
            - banolim-network

    # 4. FastAPI
    fastapi-ai:
        image: ${DOCKER_HUB_USERNAME}/banolim-ai:latest
        container_name: fastapi-ai
        restart: always
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - CHATBOT_ELEVENLABS_API_KEY=${CHATBOT_ELEVENLABS_API_KEY}
            - SENTENCE_ELEVENLABS_API_KEY=${SENTENCE_ELEVENLABS_API_KEY}
            - CLAUDE_API_KEY=${CLAUDE_API_KEY}
            - WORDBOOK_OPENAI_API_KEY=${WORDBOOK_OPENAI_API_KEY}
        networks:
            - banolim-network

networks:
    banolim-network:
        driver: bridge
